name    'zanloy-tmux'
version '0.1.0'
author 'zanloy'
license 'Apache License, Version 2.0'
summary 'A puppet class to handle tmux installation and configuration.'
project_page 'https://github.com/zanloy/puppet-tmux'
